language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install -r build-requirements.txt

script:
  - cd wineQualityPred
  - nosetests -sv --with-coverage --cover-package=wineQualityPred test.py
  
  # Build docs
  - cd ..
  - sphinx-build -b doctest doc sphinx
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - cd wineQualityPred
  - coveralls #uploads coverage report to coveralls.io
  
deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION=3.7 

  - provider: pypi
    server: https://test.pypi.org/legacy/ # Remove to deployment on pypi.org
    username: "__token__"
    password:
      secure: CRfHjkxDMNdbnnCMKfCpKX7DywvgGDrX1UJX7fE5lxcKyvQUuqqSxa0u91U/tfyck/DZkAIZKrT1G8qKDDlBGRdQFRTLqqSj2om3vd5z3ICuFEI2+l6BL0uW6uMki6TKiGGxEQuheXES48MbDdQKIY3soUIbnXJsqTEvGZ00UGqo0/7rlSHj8tPNo9/HUw2yVPZbswT68uj9PLPz+IYRW2m4pJ4zJF9Y6GS1AX70FM4kpQFFEbqus61FF00IRw+Bhej6DO2VBOqRrMaLr4J8e2BNDcM6swKrqACh7ZwhKALOHcr58AEo1D4ZnwxA/eeRaApIS9qrfaYmEo5aHtOx0meGgoRtR00X6Uhs45EebFt1xKwL/CMFARCKme2ezDHbcbW+/5W0WHR1o3iIdpwa2SWYJEA1v1rCb2JZiuVoKt72q0PevcrkVGyQpeJRsz5DKWrbKigyJU7nnSqYFoCxmb8g19d59YdwmT+C2D0yDFoX/77ztmXXAXwzzB+hOu1YSgW7xeIpp2KmUwWzCPyknJdI+ogeuA/6uZqd+Lh4i56+sgZ/W0MFeWz+z/0DNrIlhed/2mKm1KYwEbrMiJkw/QBXZ/2V4rse+dpJ3EGuy3zK9IAsqFljpXIQvQdtTjZc7c7FcOkb2NWYK3xLI2KEv9gI7K/FG/KeAJXO2EANZpU=
    on:
      branch: master
      all_branches: false
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION = 3.7"
