# From here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install -r build-requirements.txt

script:
  - nosetests -sv --with-coverage --cover-package=wineQualityPred test.py
  
  # Build docs
  - sphinx-build -b doctest doc sphinx
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls #uploads coverage report to coveralls.io
  
deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION=3.7 

    provider: pypi
    server: https://test.pypi.org/legacy/ # Remove to deployment on pypi.org
    username: "__token__"
    password:
      secure: pypi-AgENdGVzdC5weXBpLm9yZwIkNDU4ZDJlMTAtMTIyMS00Y2IyLWJhYTUtZWY3NWIyZWU5N2U5AAJAeyJwZXJtaXNzaW9ucyI6IHsicHJvamVjdHMiOiBbIndpbmVxdWFsaXR5cHJlZCJdfSwgInZlcnNpb24iOiAxfQAABiBObhjOqRpGRUPYdDBb8IQrhhNPQx78EidGwiLK0n-kCg
    on:
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION = 3.7"
